// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeT5QOfdhEcRRYXTRlnjlKX7D9v90dR1E',
    appId: '1:1043464893919:web:80a64a1149fca576fd006a',
    messagingSenderId: '1043464893919',
    projectId: 'pragmatic-blend-355802',
    authDomain: 'pragmatic-blend-355802.firebaseapp.com',
    databaseURL: 'https://pragmatic-blend-355802-default-rtdb.firebaseio.com',
    storageBucket: 'pragmatic-blend-355802.firebasestorage.app',
    measurementId: 'G-MYQX880Z8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6kEeNpybVZgLBRAEyajx_UQIBL-sU-6Q',
    appId: '1:1043464893919:android:010faf1c49f5c750fd006a',
    messagingSenderId: '1043464893919',
    projectId: 'pragmatic-blend-355802',
    databaseURL: 'https://pragmatic-blend-355802-default-rtdb.firebaseio.com',
    storageBucket: 'pragmatic-blend-355802.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbucQ9FJKEHpjGWqsK7XU6slf3Bqeu3MQ',
    appId: '1:1043464893919:ios:aeff67870aed2e1cfd006a',
    messagingSenderId: '1043464893919',
    projectId: 'pragmatic-blend-355802',
    databaseURL: 'https://pragmatic-blend-355802-default-rtdb.firebaseio.com',
    storageBucket: 'pragmatic-blend-355802.firebasestorage.app',
    androidClientId:
        '1043464893919-jl63nn5qf6dfl15cr6dhsoaj256upg03.apps.googleusercontent.com',
    iosClientId:
        '1043464893919-3oc89s9laa7v416hfse7pdqafa4r8gua.apps.googleusercontent.com',
    iosBundleId: 'com.example.redShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbucQ9FJKEHpjGWqsK7XU6slf3Bqeu3MQ',
    appId: '1:1043464893919:ios:aeff67870aed2e1cfd006a',
    messagingSenderId: '1043464893919',
    projectId: 'pragmatic-blend-355802',
    databaseURL: 'https://pragmatic-blend-355802-default-rtdb.firebaseio.com',
    storageBucket: 'pragmatic-blend-355802.firebasestorage.app',
    androidClientId:
        '1043464893919-jl63nn5qf6dfl15cr6dhsoaj256upg03.apps.googleusercontent.com',
    iosClientId:
        '1043464893919-3oc89s9laa7v416hfse7pdqafa4r8gua.apps.googleusercontent.com',
    iosBundleId: 'com.example.redShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeT5QOfdhEcRRYXTRlnjlKX7D9v90dR1E',
    appId: '1:1043464893919:web:63a70fc0b402be8afd006a',
    messagingSenderId: '1043464893919',
    projectId: 'pragmatic-blend-355802',
    authDomain: 'pragmatic-blend-355802.firebaseapp.com',
    databaseURL: 'https://pragmatic-blend-355802-default-rtdb.firebaseio.com',
    storageBucket: 'pragmatic-blend-355802.firebasestorage.app',
    measurementId: 'G-019E4NPKES',
  );
}
